spring:
  application:
    name: Tcc-eureka-server

---
spring:
  profiles: master
server:
  port: 8761
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8762/eureka/
      
--- 
spring:
  profiles: backup
server:
  port: 8762
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/